# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 281)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_to_checkitout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_to_checkitout.setGeometry(QtCore.QRect(50, 60, 141, 71))
        self.pushButton_to_checkitout.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton_to_checkitout.setObjectName("pushButton_to_checkitout")
        self.listView_what_checkitout = QtWidgets.QListView(self.centralwidget)
        self.listView_what_checkitout.setGeometry(QtCore.QRect(210, 60, 256, 192))
        self.listView_what_checkitout.setObjectName("listView_what_checkitout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_to_checkitout.setText(_translate("MainWindow", "Checkitout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
